insert into pun(pun) values ('I''d like to start with the chimney jokes – I''ve got a stack of them. The first one is on the house.');
insert into pun(pun) values ('I did a gig in a fertility clinic. I got a standing ovulation.');
insert into pun(pun) values ('I had a dream last night that I was cutting carrots with the Grim Reaper – dicing with death.');
insert into pun(pun) values ('I rang up British Telecom and said: ''I want to report a nuisance caller.'' He said: ''Not you again.''');
insert into pun(pun) values ('I saw this bloke chatting-up a cheetah and I thought: ''He''s trying to pull a fast one.''');
insert into pun(pun) values ('The advantages of easy origami are two-fold.');
insert into pun(pun) values ('I rang up my local swimming baths. I said: ''Is that the local swimming baths?'' He said: ''It depends where you''re calling from.''');
insert into pun(pun) values ('I said to the gym instructor: ''Can you teach me to do the splits?'' He said: ''How flexible are you?'' I said: ''I can''t make Tuesdays.''');
insert into pun(pun) values ('I''m against hunting. In fact, I''m a hunt saboteur. I go out the night before and shoot the fox.');
insert into pun(pun) values ('This policeman came up to me with a pencil and a piece of very thin paper. He said, ''I want you to trace someone for me.''');
insert into pun(pun) values ('I met this bloke with a didgeridoo and he was playing Dancing Queen on it. I thought, ''that''s Abba-riginal.''');
insert into pun(pun) values ('I''ve decided to sell my Hoover – it was just collecting dust.');
insert into pun(pun) values ('I was getting into my car, and this bloke says to me ''Can you give me a lift?'' I said ''Sure, you look great, the world''s your oyster, go for it.''');
insert into pun(pun) values ('I went down the local supermarket. I said: ''I want to make a complaint – this vinegar''s got lumps in it.'' He said: ''Those are pickled onions.''');
insert into pun(pun) values ('I''ll tell you what I love doing more than anything – trying to pack myself in a small suitcase. I can hardly contain myself.');
insert into pun(pun) values ('I was at sea the other day and loads of meat floated past. It was a bit choppy.');
insert into pun(pun) values ('You know, somebody actually complimented me on my driving today. They left a little note on the windscreen, it said ''Parking Fine.'' So that was nice.');
insert into pun(pun) values ('I''m so lazy I''ve got a smoke alarm with a snooze button.');
insert into pun(pun) values ('I''ve spent the afternoon re-arranging the furniture in Dracula''s house. I was doing a bit of Fang-Shui.');
insert into pun(pun) values ('I was stealing things in the supermarket today while balanced on the shoulders of vampires. I was charged with shoplifting on three counts.');
insert into pun(pun) values ('Uncle Ben has died. No more Mr Rice Guy.');
insert into pun(pun) values ('I once did a gig in a zoo. I got babooned off.');
insert into pun(pun) values ('Eric Bristow asked me why I put superglue on one of his darts. I said ''you just can''t let it go can you?''');
insert into pun(pun) values ('I saw this advert in a window that said: ''Television for sale, £1, volume stuck on full.'' I thought, ''I can''t turn that down.''');
insert into pun(pun) values ('I''ve just been on a once-in-a-lifetime holiday. I''ll tell you what, never again.');
insert into pun(pun) values ('Conjunctivitis.com – that''s a site for sore eyes.');
insert into pun(pun) values ('Do you ever get that when you''re half way through eating a horse and you think to yourself, ''I''m not as hungry as I thought I was?''');
insert into pun(pun) values ('Black Beauty – now there''s a dark horse.');
insert into pun(pun) values ('I was reading a book – ''The History of Glue'' – I couldn''t put it down.');
insert into pun(pun) values ('I got home, and the phone was ringing. I picked it up, and said ''Who''s speaking please?'' And a voice said ''You are.''');
insert into pun(pun) values ('Exit signs? They''re on the way out!');
insert into pun(pun) values ('Velcro? What a rip-off!');
insert into pun(pun) values ('I went to buy a watch, and the man in the shop said ''Analogue?'' I said ''No, just a watch.''');
insert into pun(pun) values ('I was in this restaurant and I asked for something herby. They gave me a Volkswagen with no driver.');
insert into pun(pun) values ('I went to the doctor. I said to him ''I''m frightened of lapels.'' He said, ''You''ve got cholera.''');
insert into pun(pun) values ('I met the bloke who invented crosswords today. I can''t remember his name, it''s P-something T-something R…');
insert into pun(pun) values ('I was having dinner with my boss and his wife said, ''How many potatoes would you like, Tim?''. I said ''Ooh, I''ll just have one please.'' She said ''It''s OK, you don''t have to be polite.'' ''Alright,'' I said, ''I''ll just have one then, you stupid cow.');
insert into pun(pun) values ('A friend of mine always wanted to be run over by a steam train. When it happened, he was chuffed to bits!');
insert into pun(pun) values ('I was in the army once and the Sergeant said to me: ''What does surrender mean?'' I said: ''I give up!''');
insert into pun(pun) values ('This bloke said to me: ''I''m going to attack you with the neck of a guitar.'' I said: ''Is that a fret?''');
insert into pun(pun) values ('I saw Arnold Schwarzenegger eating a chocolate egg. I said: ''I bet I know what your favourite Christian festival is.'' He said: ''You have to love Easter, baby.''');
insert into pun(pun) values ('I used go out with an anaesthetist – she was a local girl.');
insert into pun(pun) values ('Crime in multi-storey car parks. That is wrong on so many different levels.');
insert into pun(pun) values ('I went to a Pretenders concert. It was a tribute act.');
insert into pun(pun) values ('I went down my local ice-cream shop, and said ''I want to buy an ice-cream''. He said ''Hundreds & thousands?'' I said ''We''ll start with one.'' He said ''Knickerbocker glory?'' I said ''I do get a certain amount of freedom in these trousers, yes.''');
insert into pun(pun) values ('I bought a train ticket and the driver said ''Eurostar?'' I said ''Well, I''ve been on telly but I''m no Dean Martin.'' Still, at least it''s comfortable on Eurostar – it''s murder on the Orient Express.');
insert into pun(pun) values ('I went into a shop and I said, ''Can someone sell me a kettle?'' The bloke said ''Kenwood?'' I said, ''Where is he?''');
insert into pun(pun) values ('I went in to a pet shop. I said, ''Can I buy a goldfish?'' The guy said, ''Do you want an aquarium?'' I said, ''I don''t care what star sign it is.''');
insert into pun(pun) values ('You know, I''m not very good at magic – I can only do half of a trick. I''m a member of the Magic Semi-circle.');
insert into pun(pun) values ('My next door neighbour worships exhaust pipes. He''s a catholic converter.');
insert into pun(pun) values ('He said ''I''m going to chop off the bottom of one of your trouser legs and put it in a library''. I thought ''That''s a turn-up for the books.''');
insert into pun(pun) values ('And the back of his anorak was leaping up and down, and people were chucking money to him. I said ''Do you earn a living doing that?'' He said ''Yes, this is my livelihood.''');
insert into pun(pun) values ('I bought some Armageddon cheese today, and it said on the packet ''Best Before End…''');
insert into pun(pun) values ('So this bloke says to me, ''Can I come in your house and talk about your carpets?'' I thought ''That''s all I need, a Je-hoover''s witness.''');
insert into pun(pun) values ('So Batman came up to me & he hit me over the head with a vase & he went ''T''PAU!'' I said ''Don''t you mean KAPOW??'' He said ''No, I''ve got china in my hand.''');